### ISSUE TITLE
Segmentation fault requiring pipeline-minify-js for a mocha test

### ISSUE THREAD

**Issue by franciov** [kenzanlabs/pipeline-minify-js#10]
Requiring `pipeline-minify-js` [here](https://github.com/ThomsonReuters-IPS/webui-pipeline-archive-dist/pull/2/files#diff-1fdf421c05c1140f6d71444ea2b27638R4) I got the following error executing a test the first time:

```
[15:46:57] TypeError in plugin 'gulp-mocha'
Message:
    Cannot set property 'warn_function' of undefined
Stack:
TypeError: Cannot set property 'warn_function' of undefined
    at Object.<anonymous> (/Users/franciov/WebstormProjects/ThomsonReuters-IPS/webui-pipeline-archive-dist/node_modules/uglify-js/tools/node.js:42:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/franciov/WebstormProjects/ThomsonReuters-IPS/webui-pipeline-archive-dist/node_modules/gulp-uglify/index.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

then I got and keep on getting:

``
Segmentation fault: 11
```

Versions:
- pipeline-minify-js v0.4.0
- node v5.9.0
- npm v3.7.3

**Comment by obuckley-kenzan** [comment]
@franciov 
Can you provide the context / "steps to reproduce"?  Is this in a gulpfile, or being used within the context of another gulp task?

**Comment by obuckley-kenzan** [comment]
@franciov 
Although unituitive, I wonder if the issue is related to the current usage expectations of this pipeline
https://github.com/kenzanlabs/pipeline-minify-js#usage

```javascript
var minifyPipeline = require('pipeline-minify-js')();  //note the need to call the pipeline as a function immediately
```

This is something we are looking to put on the roadmap to change
https://github.com/kenzanlabs/keystone/issues/7

And something we are doing with https://github.com/kenzanlabs/pipeline-validate-js/ as we refactor it up a little bit
